import { render, screen, fireEvent } from '@testing-library/react';
import Input from '@/components/ui/Input';

describe('Input', () => {
    it('renders label when provided', () => {
        render(<Input label="Email address" />);
        expect(screen.getByText('Email address')).toBeInTheDocument();
    });

    it('links label to input via htmlFor/id', () => {
        render(<Input label="Email address" />);
        const label = screen.getByText('Email address');
        const input = screen.getByRole('textbox');
        expect(label).toHaveAttribute('for', input.id);
    });

    it('renders error message when provided', () => {
        render(<Input error="This field is required" />);
        expect(screen.getByText('This field is required')).toBeInTheDocument();
    });

    it('does not render label when not provided', () => {
        render(<Input placeholder="Type here" />);
        expect(screen.queryByRole('label')).not.toBeInTheDocument();
    });

    it('does not render error message when not provided', () => {
        render(<Input />);
        // No <p> error element should be present
        expect(screen.queryByRole('paragraph')).not.toBeInTheDocument();
    });

    it('password type shows eye toggle button', () => {
        render(<Input type="password" />);
        expect(screen.getByRole('button', { name: /show password/i })).toBeInTheDocument();
    });

    it('clicking eye toggle switches input from password to text type', () => {
        render(<Input type="password" />);
        const input = screen.getByDisplayValue('') as HTMLInputElement;
        // Initially password
        expect(input).toHaveAttribute('type', 'password');

        fireEvent.click(screen.getByRole('button', { name: /show password/i }));
        expect(input).toHaveAttribute('type', 'text');
    });

    it('clicking eye toggle a second time switches back to password type', () => {
        render(<Input type="password" />);
        const input = screen.getByDisplayValue('') as HTMLInputElement;

        fireEvent.click(screen.getByRole('button', { name: /show password/i }));
        expect(input).toHaveAttribute('type', 'text');

        fireEvent.click(screen.getByRole('button', { name: /hide password/i }));
        expect(input).toHaveAttribute('type', 'password');
    });

    it('no eye toggle button for non-password types', () => {
        render(<Input type="text" />);
        expect(screen.queryByRole('button')).not.toBeInTheDocument();
    });

    it('generates a stable id linking label to input when no id/label props given', () => {
        render(<Input />);
        const input = screen.getByRole('textbox');
        // The input must have an id attribute (generated by useId())
        expect(input).toHaveAttribute('id');
        expect(input.id).toBeTruthy();
    });

    it('uses provided id when specified', () => {
        render(<Input id="my-field" label="My Field" />);
        expect(screen.getByRole('textbox')).toHaveAttribute('id', 'my-field');
        expect(screen.getByText('My Field')).toHaveAttribute('for', 'my-field');
    });
});
