spring.application.name=job-tracker
spring.profiles.active=local

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/job_tracker}
spring.datasource.username=${DB_USERNAME:}
spring.datasource.password=${DB_PASSWORD:}
spring.jpa.hibernate.ddl-auto=update

jwt.secret=${JWT_SECRET:}
jwt.expiration=${JWT_EXPIRATION:86400000}

encryption.secret=${ENCRYPTION_SECRET:}

cookie.secure=${COOKIE_SECURE:false}